pr
js-tasks-ru/jsbasic-20221114_pashakobozev pull request #3
Opened 2022-12-01 12:50 UTC by pakoru

2022-12-01 12:51 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-01 12:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-01 13:52 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-01 14:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-12-02 15:49 UTC, SinimaWath requested changes

2022-12-02 15:49 UTC, SinimaWath commented on 2-module/3-task/index.js
> +    calculator.secondValue = b;
тут тоже стоит использовать this

2022-12-02 15:49 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return answer;
Давай тут используем map

2022-12-02 15:49 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  return result;
`return arr.filter(value => value >= a && value <= b);`

2022-12-02 15:49 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return answer.slice(0, -1);
Давай тут заиспользуем вот такую комбинацию:
```
users.filter().map().join('\n')
```

2022-12-05 12:30 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-05 15:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-12-06 13:43 UTC, SinimaWath approved these changes

2022-12-06 13:44 UTC, merged