5 module
js-tasks-ru/jsbasic-20221114_pashakobozev pull request #4
Opened 2022-12-08 10:45 UTC by pakoru

2022-12-08 10:46 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-08 13:50 UTC, SinimaWath requested changes

2022-12-08 13:50 UTC, SinimaWath commented on 5-module/2-task/index.js
> +    }
Эту запись можно упростить, используя оператор: `!` -> `text.hidden = !text.hidden`

2022-12-12 13:10 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-12 15:26 UTC, SinimaWath approved these changes

2022-12-12 15:27 UTC, merged